Repository imas/mastodon, pull requests merged in 2018-03, with the labels that each got.

#140 お気に入りタグに表示順カラム追加
  app/controllers/api/v1/favourite_tags_controller.rb
  app/controllers/settings/favourite_tags_controller.rb
  app/lib/friends/favourite_tags_extension.rb
  app/models/favourite_tag.rb
  app/views/settings/favourite_tags/_form.html.haml
  app/views/settings/favourite_tags/edit.html.haml
  app/views/settings/favourite_tags/index.html.haml
  config/locales/en.yml
  config/locales/ja-IM.yml
  config/locales/ja.yml
  config/routes.rb
  db/migrate/20180213223419_add_order_to_favourite_tags.rb
  db/schema.rb
  spec/controllers/settings/favourite_tags_controller_spec.rb
  spec/fabricators/favourite_tags_fabricator.rb
  spec/models/favourite_tags_spec.rb
Labels: enhancement

#139 Enable showing trend tags on the WebUI
  app/javascript/mastodon/actions/trend_tags.js
  app/javascript/mastodon/features/compose/components/trend_tags.js
  app/javascript/mastodon/features/compose/containers/trend_tags_container.js
  app/javascript/mastodon/features/compose/index.js
  app/javascript/mastodon/reducers/index.js
  app/javascript/mastodon/reducers/trend_tags.js
  app/javascript/styles/imastodon/compose_common.scss
  app/javascript/styles/imastodon/trend_tags.scss
  app/javascript/styles/theme_mastodon.scss
Labels: enhancement

#151 Adjust the height of the Trend Tags UI
  app/javascript/mastodon/features/compose/components/trend_tags.js
Labels: bug

#154 use a sorted set to store the trend_tags
  app/controllers/api/v1/trend_tags_controller.rb
  app/models/statuses_tag.rb
  app/workers/scheduler/trend_tags_update_scheduler.rb
  config/sidekiq.yml
Labels: enhancement, refactoring

#158 Cancel sorting trend tags in the UI side
  app/javascript/mastodon/reducers/trend_tags.js
Labels: ui

#159 foldableコンポーネントをスクロール可能に変更
  app/javascript/mastodon/components/foldable.js
Labels: ui
