Repository imas/mastodon, pull requests merged in 2018-02, with the labels that each got.

#127 make the favourite_tags list foldable
  app/javascript/mastodon/components/announcement_icon_button.js
  app/javascript/mastodon/components/fold_button.js
  app/javascript/mastodon/components/foldable.js
  app/javascript/mastodon/features/compose/components/favourite_tags.js
  app/javascript/styles/imastodon/compose_common.scss
  app/javascript/styles/imastodon/favourite_tags.scss
Labels: enhancement

#141 Style adjustment for favourite-tags
  app/javascript/mastodon/features/compose/components/favourite_tags.js
  app/javascript/styles/imastodon/compose_common.scss
  app/javascript/styles/imastodon/favourite_tags.scss
Labels: refactoring

#138 bugfix annoucements toggle icon style
  app/javascript/mastodon/features/compose/components/announcements.js
  app/javascript/styles/imastodon/about.scss
  app/javascript/styles/imastodon/announcements.scss
Labels: bug

#142 Move fold state of the favourite tags list into props
  app/javascript/mastodon/actions/favourite_tags.js
  app/javascript/mastodon/features/compose/components/favourite_tags.js
  app/javascript/mastodon/features/compose/containers/favourite_tags_container.js
  app/javascript/mastodon/reducers/favourite_tags.js
Labels: refactoring
