Repository imas/mastodon, pull requests merged in 2019-06, with the labels that each got.

#216 Revert "cancel sorting trend tags in the UI side"
  app/javascript/mastodon/reducers/trend_tags.js
Labels: bug, priority middle

#223 Fix/reduce redundant methods of media attachment
  app/models/media_attachment.rb
  lib/paperclip/png_converter.rb
  spec/models/media_attachment_spec.rb
Labels: refactoring

#224 update ハッシュタグタイムラインのタグ登録/解除ボタンを復活
  app/javascript/mastodon/features/hashtag_timeline/components/favourite_toggle.js
  app/javascript/mastodon/features/hashtag_timeline/containers/favourite_toggle_container.js
  app/javascript/mastodon/features/hashtag_timeline/index.js
Labels: ui

#229 未収載トゥートやお気に入りタグ設定のアイコンを変更
  app/javascript/mastodon/components/status.js
  app/javascript/mastodon/features/compose/components/favourite_tags.js
Labels: ui

#226 Fix style for favourite_tags_controller
  app/controllers/settings/favourite_tags_controller.rb
  app/views/settings/favourite_tags/index.html.haml
Labels: ui
